# Generated by Django 4.2.8 on 2025-12-31 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="paid_leave",
            field=models.DecimalField(decimal_places=1, default=5, max_digits=4),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("paid_leave", "Paid Leave"),
                    ("sick_leave", "Sick Leave"),
                    ("casual_leave", "Casual Leave"),
                    ("earned_leave", "Earned Leave"),
                    ("unpaid_leave", "Unpaid Leave"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeaveAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="leave_attachments/")),
                ("name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="leaves.leave",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
