# Generated by Django 4.2.8 on 2026-01-03 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(upload_to=documents.models.document_upload_path),
                ),
                ("file_size", models.CharField(max_length=50)),
                ("file_type", models.CharField(max_length=20)),
                (
                    "visible_to",
                    models.JSONField(
                        default=list,
                        help_text="List of role names that can view this document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="documents_d_title_ccf306_idx"),
                    models.Index(
                        fields=["file_type"], name="documents_d_file_ty_1bb410_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="documents_d_created_3b0a51_idx"
                    ),
                ],
            },
        ),
    ]
