# Generated by Django 4.2.8 on 2025-12-27 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(max_length=100)),
                ("job_role", models.CharField(max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("contract", "Contract"),
                            ("part_time", "Part Time"),
                            ("intern", "Intern"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_joining", models.DateField()),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="employees.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id"],
                "indexes": [
                    models.Index(
                        fields=["employee_id"], name="employees_e_employe_514cc5_idx"
                    ),
                    models.Index(
                        fields=["department"], name="employees_e_departm_e28f46_idx"
                    ),
                ],
            },
        ),
    ]
