# Generated by Django 4.2.8 on 2025-12-27 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="employee_documents/")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="employee",
            name="job_role",
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="contractor_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("on_leave", "On Leave"),
                    ("terminated", "Terminated"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="job_title",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="probation_policy",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="termination_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="termination_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employment_status"], name="employees_e_employm_b2a249_idx"
            ),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(
                fields=["employee"], name="employees_e_employe_8fba9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(
                fields=["document_type"], name="employees_e_documen_3808ed_idx"
            ),
        ),
    ]
