# Generated by Django 4.2.27 on 2026-01-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="department",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="location",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="settings_de_code_de3a46_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["status"], name="settings_de_status_20d1ec_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["code"], name="settings_lo_code_416118_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["status"], name="settings_lo_status_7fb4f7_idx"),
        ),
    ]
