# Generated by Django 4.2.8 on 2025-12-31 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_add_allocation_percentage_and_role_choices"),
        ("timesheets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_description", models.CharField(max_length=255)),
                (
                    "sun_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "mon_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "tue_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "wed_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "thu_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "fri_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "sat_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="timesheets.timesheet",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="TimesheetEntry",
        ),
        migrations.AddIndex(
            model_name="timesheetrow",
            index=models.Index(
                fields=["timesheet"], name="timesheets__timeshe_1b0c6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetrow",
            index=models.Index(
                fields=["project"], name="timesheets__project_fa04e6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timesheetrow",
            unique_together={("timesheet", "project", "task_description")},
        ),
    ]
