# Generated by Django 4.2.8 on 2025-12-27 20:35

from django.db import migrations


def create_roles(apps, schema_editor):
    """Create default roles."""
    Role = apps.get_model('accounts', 'Role')
    
    roles = [
        {
            'name': 'employee',
            'display_name': 'Employee',
            'description': 'Regular employee with basic access'
        },
        {
            'name': 'reporting_manager',
            'display_name': 'Reporting Manager',
            'description': 'Manager responsible for team members'
        },
        {
            'name': 'project_lead',
            'display_name': 'Project Lead',
            'description': 'Lead of a project team'
        },
        {
            'name': 'project_manager',
            'display_name': 'Project Manager',
            'description': 'Manager of project operations and resources'
        },
        {
            'name': 'hr_user',
            'display_name': 'HR User',
            'description': 'Human Resources user with HR access'
        },
        {
            'name': 'finance_user',
            'display_name': 'Finance User',
            'description': 'Finance user with financial data access'
        },
        {
            'name': 'system_admin',
            'display_name': 'System Admin',
            'description': 'System administrator with full access'
        },
    ]
    
    for role_data in roles:
        Role.objects.get_or_create(
            name=role_data['name'],
            defaults={
                'display_name': role_data['display_name'],
                'description': role_data['description'],
            }
        )


def reverse_roles(apps, schema_editor):
    """Remove default roles."""
    Role = apps.get_model('accounts', 'Role')
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role_userrole_role_accounts_ro_name_183ba5_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(create_roles, reverse_roles),
    ]
